application:
  name: jhipster-sample-app
  project: jhipster-sample-app-project
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: jhipster-sample-app
    paths:
    - /*
